export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_LOADED = 'SEARCH_LOADED';

export const USER_LOADING = 'USER_LOADING';
export const USER_ERROR = 'USER_ERROR';
export const USER_LOADED = 'USER_LOADED';

export const REPOS_LOADING = 'REPOS_LOADING';
export const REPOS_ERROR = 'REPOS_ERROR';
export const REPOS_LOADED = 'REPOS_LOADED';

export const REPO_LOADING = 'REPO_LOADING';
export const REPO_ERROR = 'REPO_ERROR';
export const REPO_LOADED = 'REPO_LOADED';

export const COMMITS_LOADING = 'COMMITS_LOADING';
export const COMMITS_ERROR = 'COMMITS_ERROR';
export const COMMITS_LOADED = 'COMMITS_LOADED';

export const CONTRIBUTORS_LOADING = 'CONTRIBUTORS_LOADING';
export const CONTRIBUTORS_ERROR = 'CONTRIBUTORS_ERROR';
export const CONTRIBUTORS_LOADED = 'CONTRIBUTORS_LOADED';

export const LANGUAGES_LOADING = 'LANGUAGES_LOADING';
export const LANGUAGES_ERROR = 'LANGUAGES_ERROR';
export const LANGUAGES_LOADED = 'LANGUAGES_LOADED';